### ISSUE TITLE
LEMP Stack and Transmission

### ISSUE THREAD

**Issue by lewisgoddard** [orschiro/ppa-software-list#3]
`sudo apt-add-repository ppa:nginx/stable`
`sudo apt-add-repository ppa:ondrej/nginx`
`sudo apt-add-repository ppa:ondrej/php5-5.6`
`sudo apt-add-repository ppa:transmissionbt/ppa`

**Comment by orschiro** [comment]
Thanks! 

Merged: https://github.com/orschiro/ppa-software-list/commit/2b524a11d80a2b2ddec68995443e445a61e03393
